# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'timeout', '~> 0.1.0'

gem 'tty-screen', '~> 0.7.1'

gem 'tty-cursor', '~> 0.7.1'

gem 'faker', '~> 2.11'

gem 'colorize', '~> 0.8.1'

gem 'test-unit', '~> 3.3'
